// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "configuration/index.mdx": () => import("../content/docs/configuration/index.mdx?collection=docs"), "deployment/index.mdx": () => import("../content/docs/deployment/index.mdx?collection=docs"), "features/battle-arena.mdx": () => import("../content/docs/features/battle-arena.mdx?collection=docs"), "features/checkout-flow.mdx": () => import("../content/docs/features/checkout-flow.mdx?collection=docs"), "features/index.mdx": () => import("../content/docs/features/index.mdx?collection=docs"), "features/location-map.mdx": () => import("../content/docs/features/location-map.mdx?collection=docs"), "features/order-lifecycle.mdx": () => import("../content/docs/features/order-lifecycle.mdx?collection=docs"), "features/password-reset.mdx": () => import("../content/docs/features/password-reset.mdx?collection=docs"), "features/payment-architecture.mdx": () => import("../content/docs/features/payment-architecture.mdx?collection=docs"), "features/payment-integration.mdx": () => import("../content/docs/features/payment-integration.mdx?collection=docs"), "features/shipping-guide.mdx": () => import("../content/docs/features/shipping-guide.mdx?collection=docs"), "guides/index.mdx": () => import("../content/docs/guides/index.mdx?collection=docs"), "integrations/index.mdx": () => import("../content/docs/integrations/index.mdx?collection=docs"), "api/index.mdx": () => import("../content/docs/api/index.mdx?collection=docs"), "api/rest-api.mdx": () => import("../content/docs/api/rest-api.mdx?collection=docs"), "getting-started/database-setup.mdx": () => import("../content/docs/getting-started/database-setup.mdx?collection=docs"), "getting-started/environment-setup.mdx": () => import("../content/docs/getting-started/environment-setup.mdx?collection=docs"), "getting-started/index.mdx": () => import("../content/docs/getting-started/index.mdx?collection=docs"), }),
};
export default browserCollections;